---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: botflow-production-ingress
  namespace: botflow-production
  labels:
    app: botflow-production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # turn off ssl redirect for external.
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: botflow.lappis.rocks
    http:
      paths:
      - backend:
          serviceName: botflow-production
          servicePort: 80
  tls:
  - hosts:
    - botflow.lappis.rocks
    secretName: botflow-production-letsencrypt-prod-crt
---
apiVersion: v1
kind: Service
metadata:
  name: botflow-production-svc
  namespace: botflow-production
  labels:
    app: botflow-production
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: botflow-production
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: botflow-production
  namespace: botflow-production
  labels:
    app: botflow-production
spec:
  selector:
    matchLabels:
      app: botflow-production
  replicas: 1
  template:
    metadata:
      labels:
        app: botflow-production
    spec:
      containers:
      - name: botflow-production
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3000
          protocol: TCP
