name: CI

on: [pull_request]

jobs:
  build:
    env:
      working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Build
        run: |
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t bot-flow .
        working-directory: ${{env.working-directory}}
  test:
    env:
      working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          yarn install
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: |
          yarn test --ci --coverage --color
        working-directory: ${{env.working-directory}}
  lint:
    env:
      working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          yarn install
        working-directory: ${{env.working-directory}}
      - name: Run eslint
        run: |
          yarn lint
        working-directory: ${{env.working-directory}}